### ISSUE TITLE
Add Design for a Runner for Kubernetes

### ISSUE THREAD

**Issue by sub-mod** [mlperf/mlbox#111]

**Comment by swiftdiaries** [comment]
Proposal: http://bit.ly/box-k8s-runner
PR with k8s runner implementation: https://github.com/mlperf/mlbox/pull/124

**Comment by sergey-serebryakov** [comment]
@swiftdiaries Should this thread be closed?

**Comment by swiftdiaries** [comment]
Yeah, this can be closed
