### ISSUE TITLE
Add Documentation for different runners for release 0.1

### ISSUE THREAD

**Issue by sub-mod** [mlperf/mlbox#49]
Add Documentation for different runners for release 0.1
Current runners for 0.1 release are:

- [ ] ssh runner
- [ ] docker runner
- [ ] Kubernetes runner
PRs needed for each.

**Comment by xyhuang** [comment]
we will have a runner spec to guide the runner standard, which should make documentation easier for individual runners. we will probably have a discussion on that this week.

**Comment by sergey-serebryakov** [comment]
SSH and Docker runners are implemented in #77.

**Comment by sergey-serebryakov** [comment]
Done.
