### ISSUE TITLE
Prepare Hello World Run Tutorial 

### ISSUE THREAD

**Issue by bitfort** [mlperf/mlbox#61]
Make a tutorial how to do the hello world box with the pip install commands (walking through how to run it).

Basically, the steps could look like:

1. Setup host (install docker, mlbox, etc.)
2. Download the hello world box
3. Run the box, modifying inputs / reading outputs
4. Make small change to the box and re-build?

**Comment by sergey-serebryakov** [comment]
Implemented in #77.
