### ISSUE TITLE
Documenting Directory structure

### ISSUE THREAD

**Issue by sub-mod** [mlperf/mlbox#67]
Documenting Director structure
@swiftdiaries

**Comment by sergey-serebryakov** [comment]
@swiftdiaries @bitfort @sub-mod @xyhuang @sergey-serebryakov 
We just quickly discussed the directory structure. Given the proposed one [here](https://github.com/mlperf/mlbox/pull/65#issuecomment-678550860) by Adhita , Victor suggested to have top level packages for `mlcommons_box` and runners. Xinyuan suggested to have a common/lib directory for common code used in reference runners. 

Adhita, what is the motivation for using `src` directory in your proposal?
We wanted to quickly finalize on the structure here and then update merge #65.

Does this look like what we discussed? Not all files are show here.
```
mlcommons_box/
	mlcommons_box/
		common/
			# Common code for reference and other runners
			__init__.py
			...
		schemas/
			__init__.py
			mlbox-docker.yaml
			...
		check.py
		main.py
		parse.py
	requirements.txt
	setup.py
	
mlbox_ssh_run/
	mlbox_ssh_run/
		__init__.py
		main.py
	requirements.txt
	setup.py

mlbox_docker_run/
	mlbox_docker_run/
		__init__.py
		main.py
	requirements.txt
	setup.py

README.md
LICENSE
CONTRIBUTING.md

```

**Comment by swiftdiaries** [comment]
Hey @sergey-serebryakov @bitfort @xyhuang 

With the plugin architecture, I wanted to address 
1. Make reference runners installable along with the `mlcommons_box` pip package. With something like, `pip install mlcommons_box[docker,ssh|all]` with `all` to install all the runners.
2. Clearly separate runners into their own sub-directory.

May I suggest something like this?
```
mlcommons_box/
	mlcommons_box/
		common/
			# Common code for reference and other runners
			__init__.py
			...
		schemas/
			__init__.py
			mlbox-docker.yaml
			...
		check.py
		main.py
		parse.py
	requirements.txt
	setup.py

runners/	
    mlbox_ssh_run/
	mlbox_ssh_run/
		__init__.py
		main.py
	requirements.txt
	setup.py
    mlbox_docker_run/
	mlbox_docker_run/
		__init__.py
		main.py
	requirements.txt
	setup.py

examples/
    mnist/
    recommendation/
README.md
LICENSE
CONTRIBUTING.md
```

**Comment by sergey-serebryakov** [comment]
I'll vote for it. I just realized that when you add other directories into the picture such as `examples` and `docs`, having dedicated top-level directory for runners makes it look nicer.

**Comment by sub-mod** [comment]
Kindly update PR code with this directory structure @swiftdiaries

**Comment by swiftdiaries** [comment]
I've updated with the changes suggested, PTAL

**Comment by sergey-serebryakov** [comment]
Thanks @swiftdiaries It looks OK to me, and we'll refactor runners directories in their PRs. Who has the power to approve it?

**Comment by swiftdiaries** [comment]
I think @sub-mod has write access

**Comment by sub-mod** [comment]
I think we can close this issue now. @sergey-serebryakov let us know if you are unblocked now ?

**Comment by sergey-serebryakov** [comment]
@sub-mod Yes, thanks!
